GET http://localhost:3000/recepts

###

GET http://localhost:3000/recepts/5d5cf4be4f03822d1822e86a

###

POST http://localhost:3000/recepts
Content-Type: application/json

{
    "name": "Cake",
    "ingredients": ["strawberry","kiwi"]
}

###

DELETE http://localhost:3000/recepts/5d5a5e30e2c21332146426fb

###

PATCH http://localhost:3000/recepts/5d5a5e30e2c21332146426fb
Content-Type: application/json

{
    "name": "Best One",
    "ingredients": ["apple","banana"]
}

###

GET http://localhost:3000/recepts/search/Second